spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_application?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  server:
    port: 8080

  mail:
    host: smtp.gmail.com
    port: 587
    username: maharaja2632002@gmail.com
    password: mqij epxz gtxp uhra
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  account_sid: AC3da114be888d72284da42adcd01a681a
  auth_token: e7e8ab62f52895ed085beae600bbc553
  trial_number: +12564084579

